---
title: "Vacant Parcels in the City of Dallas"
output:
  distill::distill_article:
    toc: TRUE
    theme: theme.css
---

```{r, Set-Up Block, include=FALSE}
library(sf)
library(tidyverse)
library(leaflet)
library(CPALtools)

cityVacant <- st_read("data/Public Land in the City of Dallas.geojson")

citySm <- cityVacant %>%
  select(GIS_PARCEL_ID, ACCOUNT_NUM, STREET_NUM, FULL_STREET_NAME, PROPERTY_CITY, PROPERTY_ZIPCODE, OWNERSHIP_GROUP, LAND_VAL, PREV_MKT_VAL, SPTD_CODE) %>%
  mutate(ZIP = str_extract(PROPERTY_ZIPCODE, "^\\d{5}")) %>%
  st_transform(crs = 4326)

dallasBound <- st_read("data/City of Dallas Boundary.geojson") %>%
  st_transform(crs = 4326)
```

The map below visualizes the vacant land within the boundaries of the City of Dallas currently owned by public agencies such as the City of Dallas, Dallas County, DART, and Dallas ISD, among others using 2021 DCAD Certified rolls.

```{r, Publicly Owned Vacant Land, echo = FALSE, message=FALSE, warning=FALSE, layout="l-body-outset", fig.height=8, fig.width=8}
popup <- paste0("<b>", "Account Number: ", "</b>", citySm$ACCOUNT_NUM, "<br>",
                "<b>", "Account Owner: ", "</b>", citySm$OWNERSHIP_GROUP, "<br>",
                "<b>", "Address: ", "</b>", citySm$STREET_NUM, " ", citySm$FULL_STREET_NAME, "<br>",
                "<b>", "City: ", "</b>", citySm$PROPERTY_CITY, "<br>",
                "<b>", "Zip: ", "</b>", citySm$ZIP, "<br>",
                "<b>", "Current Land Value: ", "</b>", scales::dollar(citySm$LAND_VAL), "<br>",
                "<b>", "Previous Market Value: ", "</b>", scales::dollar(citySm$PREV_MKT_VAL), "<br>",
                "<b>", "SPTD Code: ", "</b>", citySm$SPTD_CODE, "<br>"
               )

cityDallas <- citySm %>%
  filter(OWNERSHIP_GROUP == "CITY OF DALLAS")

countyDallas <- citySm %>%
  filter(OWNERSHIP_GROUP == "DALLAS COUNTY")

isdDallas <- citySm %>%
  filter(OWNERSHIP_GROUP == "DALLAS ISD")

multiple <- citySm %>%
  filter(OWNERSHIP_GROUP == "MULTIPLE OWNERS")

haDallas <- citySm %>%
  filter(OWNERSHIP_GROUP == "DALLAS HOUSING AUTHORITY")

dart <- citySm %>%
  filter(OWNERSHIP_GROUP == "DART")

collegeDallas <- citySm %>%
  filter(OWNERSHIP_GROUP == "DALLAS COLLEGE")

leaflet() %>%
#  setView(lng = -96.7970, lat = 32.7767, zoom = 10) %>%
  addTiles(urlTemplate = cpal_mapbox, attribution = cpal_leaflet) %>%
  addPolygons(data = dallasBound,
              fillColor = "#595959",
              color = "#595959",
              weight = 2,
              opacity = 1,
              fillOpacity = 0
              ) %>%
  addPolygons(data = cityDallas,
              fillColor = "#008097",
              color = "#595959",
              weight = 0.5,
              opacity = 0.8,
              fillOpacity = 0.4,
              group = "City of Dallas",
              popup = ~popup,
              highlightOptions = highlightOptions(color = "white", 
                                                  weight = 2,
                                                  bringToFront = TRUE)
              ) %>%
  addPolygons(data = countyDallas,
              fillColor = "#E98816",
              color = "#595959",
              weight = 0.5,
              opacity = 0.8,
              fillOpacity = 0.4,
              group = "Dallas County",
              popup = ~popup,
              highlightOptions = highlightOptions(color = "white", 
                                                  weight = 2,
                                                  bringToFront = TRUE)
              ) %>%
  addPolygons(data = isdDallas,
              fillColor = "#EA8B98",
              color = "#595959",
              weight = 0.5,
              opacity = 0.8,
              fillOpacity = 0.4,
              group = "Dallas ISD",
              popup = ~popup,
              highlightOptions = highlightOptions(color = "white", 
                                                  weight = 2,
                                                  bringToFront = TRUE)
              ) %>%
  addPolygons(data = multiple,
              fillColor = "#EACA2D",
              color = "#595959",
              weight = 0.5,
              opacity = 0.8,
              fillOpacity = 0.4,
              group = "Multiple Owners",
              popup = ~popup,
              highlightOptions = highlightOptions(color = "white", 
                                                  weight = 2,
                                                  bringToFront = TRUE)
              ) %>%
  addPolygons(data = haDallas,
              fillColor = "#851E2C",
              color = "#595959",
              weight = 0.5,
              opacity = 0.8,
              fillOpacity = 0.4,
              group = "Dallas Housing Authority",
              popup = ~popup,
              highlightOptions = highlightOptions(color = "white", 
                                                  weight = 2,
                                                  bringToFront = TRUE)
              ) %>%
    addPolygons(data = dart,
              fillColor = "#1E4A4A",
              color = "#595959",
              weight = 0.5,
              opacity = 0.8,
              fillOpacity = 0.4,
              group = "DART",
              popup = ~popup,
              highlightOptions = highlightOptions(color = "white", 
                                                  weight = 2,
                                                  bringToFront = TRUE)
              ) %>%
    addPolygons(data = collegeDallas,
              fillColor = "#F7314C",
              color = "#595959",
              weight = 0.5,
              opacity = 0.8,
              fillOpacity = 0.4,
              group = "Dallas College",
              popup = ~popup,
              highlightOptions = highlightOptions(color = "white", 
                                                  weight = 2,
                                                  bringToFront = TRUE)
              ) %>%
  addLayersControl(
    overlayGroups = c("City of Dallas",
                      "Dallas County",
                      "Dallas ISD",
                      "DART",
                      "Dallas Housing Authority",
                      "Dallas College",
                      "Multiple Owners"),
    position = "topright",
    options = layersControlOptions(collapsed = FALSE))
```
